# Generated by Django 5.2.8 on 2025-12-04 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='address',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='city',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='country',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='state',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='agent',
            name='agent_papers',
            field=models.FileField(blank=True, help_text='Agent certificate or documents', null=True, upload_to='agent_papers/'),
        ),
        migrations.AddField(
            model_name='agent',
            name='license_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
