# Generated by Django 5.2.8 on 2025-12-07 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_remove_agent_address_remove_agent_bio_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='agent_groups', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='agent_permissions', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
