# Generated by Django 5.2.8 on 2025-12-12 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_alter_agent_groups_alter_agent_user_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentPrivacySecurity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collect_basic_info', models.BooleanField(default=True, help_text='Collect name, email, phone number, login details')),
                ('collect_activity_logs', models.BooleanField(default=True, help_text='Collect activity logs and platform usage')),
                ('collect_chat_messages', models.BooleanField(default=True, help_text='Collect chat messages and communications')),
                ('collect_documents', models.BooleanField(default=True, help_text='Collect uploaded documents for compliance')),
                ('collect_optional_info', models.BooleanField(default=False, help_text='Collect optional identity verification and files')),
                ('use_for_services', models.BooleanField(default=True, help_text='Use data to provide services')),
                ('use_for_alerts', models.BooleanField(default=True, help_text='Send alerts about offers and updates')),
                ('use_for_compliance', models.BooleanField(default=True, help_text='Use data for platform security and compliance')),
                ('share_with_partners', models.BooleanField(default=True, help_text='Share with trusted service providers and legal authorities')),
                ('allow_multi_factor_auth', models.BooleanField(default=True, help_text='Enable multi-factor authentication')),
                ('encrypted_communication', models.BooleanField(default=True, help_text='Use HTTPS/SSL encryption')),
                ('data_retention_months', models.IntegerField(default=24, help_text='Keep data for X months unless legally required')),
                ('allow_data_deletion', models.BooleanField(default=True, help_text='Allow user to request data deletion')),
                ('privacy_policy_accepted', models.BooleanField(default=False, help_text='User has accepted privacy policy')),
                ('privacy_policy_version', models.CharField(default='1.0', help_text='Version of accepted privacy policy', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_security', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agent Privacy & Security',
                'verbose_name_plural': 'Agent Privacy & Security',
            },
        ),
    ]
