# Generated by Django 5.2.8 on 2025-12-18 04:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0005_agenttermsconditions'),
        ('seller', '0009_propertydocument_agreement_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Property title', max_length=255)),
                ('street_address', models.CharField(help_text='Street address', max_length=255)),
                ('city', models.CharField(help_text='City', max_length=100)),
                ('state', models.CharField(help_text='State', max_length=50)),
                ('zip_code', models.CharField(help_text='ZIP code', max_length=20)),
                ('property_type', models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('condo', 'Condominium'), ('townhouse', 'Townhouse'), ('land', 'Land'), ('commercial', 'Commercial'), ('other', 'Other')], default='house', help_text='Type of property', max_length=20)),
                ('bedrooms', models.IntegerField(blank=True, help_text='Number of bedrooms', null=True)),
                ('bathrooms', models.DecimalField(blank=True, decimal_places=1, help_text='Number of bathrooms', max_digits=3, null=True)),
                ('square_feet', models.IntegerField(blank=True, help_text='Square footage', null=True)),
                ('description', models.TextField(blank=True, help_text='Property description', null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Listing price in dollars', max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('published', 'Published'), ('sold', 'Sold'), ('archived', 'Archived')], default='draft', help_text='Listing status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_listings', to=settings.AUTH_USER_MODEL)),
                ('property_document', models.OneToOneField(help_text='Property document with accepted selling agreement', on_delete=django.db.models.deletion.CASCADE, related_name='listing', to='seller.propertydocument')),
            ],
            options={
                'verbose_name': 'Property Listing',
                'verbose_name_plural': 'Property Listings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyListingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(help_text='Document file (PDF, JPG, PNG, max 10MB)', upload_to='listing_documents/%Y/%m/')),
                ('document_type', models.CharField(choices=[('deed', 'Property Deed'), ('inspection', 'Inspection Report'), ('appraisal', 'Appraisal Report'), ('floor_plan', 'Floor Plan'), ('other', 'Other Document')], default='other', help_text='Type of document', max_length=20)),
                ('title', models.CharField(help_text='Document title', max_length=255)),
                ('file_size', models.BigIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_documents', to='agent.propertylisting')),
            ],
            options={
                'verbose_name': 'Property Listing Document',
                'verbose_name_plural': 'Property Listing Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyListingPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(help_text='Property photo (JPG, PNG, max 10MB)', upload_to='property_photos/%Y/%m/')),
                ('caption', models.CharField(blank=True, help_text='Photo caption', max_length=255, null=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Is this the primary/featured photo')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('file_size', models.BigIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='agent.propertylisting')),
            ],
            options={
                'verbose_name': 'Property Listing Photo',
                'verbose_name_plural': 'Property Listing Photos',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
