# Generated by Django 5.2.4 on 2025-12-22 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0006_propertylisting_propertylistingdocument_and_more'),
        ('seller', '0010_agentnotification_agent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertylisting',
            name='property_document',
            field=models.OneToOneField(blank=True, help_text='Property document with accepted selling agreement (optional for admin-created listings)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listing', to='seller.propertydocument'),
        ),
    ]
