# Generated by Django 5.2.4 on 2025-12-24 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0007_alter_propertylisting_property_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='area_of_expertise',
            field=models.TextField(blank=True, help_text='Areas of expertise (e.g., residential, commercial)', null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='availability',
            field=models.CharField(blank=True, choices=[('full-time', 'Full-time'), ('part-time', 'Part-time'), ('project-based', 'Project-Based')], default='full-time', help_text='Agent availability type', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='company_details',
            field=models.CharField(blank=True, help_text='Real estate company or firm name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='languages',
            field=models.TextField(blank=True, help_text='Languages spoken (comma-separated)', null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='years_of_experience',
            field=models.IntegerField(blank=True, help_text='Years of experience in real estate', null=True),
        ),
    ]
