# Generated by Django 5.2.4 on 2025-12-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0008_agent_area_of_expertise_agent_availability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='about',
            field=models.TextField(blank=True, help_text='Tell clients about yourself (max 500 characters)', null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='property_types',
            field=models.JSONField(blank=True, default=list, help_text="Property types handled (array of strings, e.g., ['Single Family', 'Condos', 'Townhouses'])"),
        ),
        migrations.AddField(
            model_name='agent',
            name='service_areas',
            field=models.JSONField(blank=True, default=list, help_text="Service areas (array of strings, e.g., ['Springfield', 'Downtown', 'Suburban Areas'])"),
        ),
        migrations.AlterField(
            model_name='agent',
            name='languages',
            field=models.JSONField(blank=True, default=list, help_text="Languages spoken (array of strings, e.g., ['English', 'Spanish', 'French'])"),
        ),
    ]
