# Generated by Django 5.2.4 on 2025-12-28 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0009_agent_about_agent_property_types_agent_service_areas_and_more'),
        ('buyer', '0012_remove_buyerdocument_document_and_more'),
        ('messaging', '0001_initial'),
        ('seller', '0017_populate_cma_documents'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='conversation',
            name='messaging_c_seller__043109_idx',
        ),
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='conversation',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations_as_buyer', to='buyer.buyer'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='property_listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='agent.propertylisting'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='showing_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='buyer.showingschedule'),
        ),
        migrations.AddField(
            model_name='message',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages_as_buyer', to='buyer.buyer'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='conversation_type',
            field=models.CharField(choices=[('selling_request', 'Selling Request Discussion'), ('showing_inquiry', 'Property Showing Inquiry'), ('general', 'General Discussion')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations_as_seller', to='seller.seller'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_type',
            field=models.CharField(choices=[('agent', 'Agent'), ('seller', 'Seller'), ('buyer', 'Buyer')], max_length=10),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['agent', 'buyer'], name='messaging_c_agent_i_350435_idx'),
        ),
    ]
