# Generated by Django 5.2.8 on 2025-12-10 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('seller', '0005_agentnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_user_id', models.PositiveIntegerField()),
                ('other_user_type', models.CharField(choices=[('buyer', 'Buyer'), ('agent', 'Agent')], help_text='Type of other participant', max_length=10)),
                ('conversation_type', models.CharField(choices=[('seller_buyer', 'Seller-Buyer'), ('seller_agent', 'Seller-Agent')], default='seller_buyer', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_conversations', to='seller.seller')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.PositiveIntegerField()),
                ('sender_type', models.CharField(choices=[('seller', 'Seller'), ('buyer', 'Buyer'), ('agent', 'Agent')], max_length=10)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('file', 'File')], default='text', max_length=10)),
                ('content', models.TextField()),
                ('file_url', models.URLField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='common.conversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField()),
                ('user_type', models.CharField(choices=[('seller', 'Seller'), ('buyer', 'Buyer'), ('agent', 'Agent')], max_length=10)),
                ('unread_count', models.PositiveIntegerField(default=0)),
                ('is_muted', models.BooleanField(default=False)),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='common.conversation')),
            ],
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['seller', '-updated_at'], name='common_conv_seller__f06380_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['other_user_id', '-updated_at'], name='common_conv_other_u_aa73a8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together={('seller', 'other_user_id', 'other_user_type')},
        ),
        migrations.AddIndex(
            model_name='conversationparticipant',
            index=models.Index(fields=['conversation', 'user_id'], name='common_conv_convers_85a580_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='conversationparticipant',
            unique_together={('conversation', 'user_id', 'user_type')},
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', '-created_at'], name='common_mess_convers_7a4ccb_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender_id', 'sender_type'], name='common_mess_sender__f861ab_idx'),
        ),
    ]
