# Generated by Django 5.2.4 on 2025-12-27 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_conversation_conversationparticipant_message_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.AlterUniqueTogether(
            name='conversationparticipant',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='conversationparticipant',
            name='conversation',
        ),
        migrations.DeleteModel(
            name='ConversationParticipant',
        ),
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='seller',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
    ]
