# Generated by Django 5.2.4 on 2025-12-27 06:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_conversation_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('terms_conditions', 'Terms & Conditions'), ('privacy_policy', 'Privacy Policy'), ('buyer_terms', 'Buyer Terms & Policy'), ('seller_terms', 'Seller Terms & Policy'), ('agent_terms', 'Agent Terms & Policy')], help_text='Type of legal document', max_length=50)),
                ('user_type', models.CharField(choices=[('all', 'All Users'), ('agent', 'Agents'), ('seller', 'Sellers'), ('buyer', 'Buyers')], default='all', help_text='Target user type for this document', max_length=20)),
                ('title', models.CharField(help_text='Document title', max_length=255)),
                ('content', models.TextField(help_text='Full document content (supports HTML)')),
                ('version', models.CharField(default='1.0', help_text='Document version number', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Only active documents are shown to users')),
                ('effective_date', models.DateField(default=django.utils.timezone.now, help_text='Date when this version becomes effective')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin who created this document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_legal_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Legal Document',
                'verbose_name_plural': 'Legal Documents',
                'ordering': ['-created_at'],
                'unique_together': {('document_type', 'user_type', 'is_active')},
            },
        ),
    ]
