# Generated by Django 5.2.4 on 2025-12-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_legaldocument'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='legaldocument',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='legaldocument',
            name='document_type',
            field=models.CharField(choices=[('agent_privacy_policy', 'Agent Privacy Policy'), ('agent_terms_conditions', 'Agent Terms & Conditions'), ('seller_privacy_policy', 'Seller Privacy Policy'), ('seller_terms_conditions', 'Seller Terms & Conditions'), ('buyer_privacy_policy', 'Buyer Privacy Policy'), ('buyer_terms_conditions', 'Buyer Terms & Conditions')], help_text='Type of legal document - each type can only have one active document', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='legaldocument',
            name='user_type',
            field=models.CharField(choices=[('agent', 'Agents'), ('seller', 'Sellers'), ('buyer', 'Buyers')], help_text='Target user type for this document (auto-determined from document_type)', max_length=20),
        ),
    ]
