# Generated by Django 5.2.4 on 2025-12-27 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentPrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(help_text='Privacy policy content (supports HTML)')),
                ('version', models.CharField(default='1.0', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_agent_privacy_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agent Privacy Policy',
                'verbose_name_plural': 'Agent Privacy Policies',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='AgentTermsConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(help_text='Terms & conditions content (supports HTML)')),
                ('version', models.CharField(default='1.0', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_agent_terms_conditions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agent Terms & Conditions',
                'verbose_name_plural': 'Agent Terms & Conditions',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='BuyerPrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(help_text='Privacy policy content (supports HTML)')),
                ('version', models.CharField(default='1.0', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_buyer_privacy_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Buyer Privacy Policy',
                'verbose_name_plural': 'Buyer Privacy Policies',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='BuyerTermsConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(help_text='Terms & conditions content (supports HTML)')),
                ('version', models.CharField(default='1.0', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_buyer_terms_conditions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Buyer Terms & Conditions',
                'verbose_name_plural': 'Buyer Terms & Conditions',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='SellerPrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(help_text='Privacy policy content (supports HTML)')),
                ('version', models.CharField(default='1.0', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_seller_privacy_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seller Privacy Policy',
                'verbose_name_plural': 'Seller Privacy Policies',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='SellerTermsConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(help_text='Terms & conditions content (supports HTML)')),
                ('version', models.CharField(default='1.0', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_seller_terms_conditions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seller Terms & Conditions',
                'verbose_name_plural': 'Seller Terms & Conditions',
                'ordering': ['-effective_date'],
            },
        ),
    ]
