# Generated by Django 5.2.4 on 2025-12-28 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('mortgage_letter', 'Mortgage Letter'), ('cma_report', 'CMA Report'), ('showing_agreement', 'Showing Agreement'), ('selling_agreement', 'Selling Agreement'), ('buyer_agreement', 'Buyer Agreement')], help_text='Type of document', max_length=50)),
                ('title', models.CharField(help_text='Document title', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Document description or notes', null=True)),
                ('document', models.FileField(help_text='Document file (PDF, JPG, PNG supported)', upload_to='platform_documents/%Y/%m/%d/')),
                ('file_size', models.BigIntegerField(default=0, editable=False, help_text='File size in bytes')),
                ('is_active', models.BooleanField(default=True, help_text='Is this document currently active?')),
                ('version', models.CharField(default='1.0', help_text='Document version', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_platform_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Platform Document',
                'verbose_name_plural': 'Platform Documents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['document_type', 'is_active'], name='superadmin__documen_a8c208_idx'), models.Index(fields=['-created_at'], name='superadmin__created_aec10e_idx')],
            },
        ),
    ]
