# Generated by Django 5.2.8 on 2025-12-08 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selling_reason', models.TextField(help_text='Reason for selling the property')),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
                ('asking_price', models.DecimalField(decimal_places=2, help_text='Asking price in dollars', max_digits=12)),
                ('start_date', models.DateField(help_text='When the selling period starts')),
                ('end_date', models.DateField(help_text='When the selling period ends')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', help_text='Status of the selling request', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selling_requests', to='seller.seller')),
            ],
            options={
                'verbose_name': 'Selling Request',
                'verbose_name_plural': 'Selling Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
