# Generated by Django 5.2.8 on 2025-12-09 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_sellingrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('approved', 'Selling Request Approved'), ('rejected', 'Selling Request Rejected'), ('cma_ready', 'CMA Report Ready'), ('agreement', 'Selling Agreement')], default='approved', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('action_url', models.CharField(blank=True, help_text='URL for action button', max_length=500, null=True)),
                ('action_text', models.CharField(blank=True, help_text='Text for action button', max_length=100, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='seller.seller')),
                ('selling_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='seller.sellingrequest')),
            ],
            options={
                'verbose_name': 'Seller Notification',
                'verbose_name_plural': 'Seller Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
