# Generated by Django 5.2.8 on 2025-12-09 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_sellernotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('cma', 'CMA Report'), ('inspection', 'Inspection Report'), ('appraisal', 'Appraisal Report'), ('other', 'Other Document')], default='cma', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to='property_documents/%Y/%m/%d/')),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_documents', to='seller.seller')),
                ('selling_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='seller.sellingrequest')),
            ],
            options={
                'verbose_name': 'Property Document',
                'verbose_name_plural': 'Property Documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
