# Generated by Django 5.2.8 on 2025-12-09 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_propertydocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('document_uploaded', 'Seller Uploaded Document'), ('cma_requested', 'CMA Requested'), ('document_updated', 'Document Updated'), ('new_selling_request', 'New Selling Request')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('action_url', models.CharField(blank=True, max_length=500, null=True)),
                ('action_text', models.CharField(blank=True, max_length=100, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_notifications', to='seller.propertydocument')),
                ('selling_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_notifications', to='seller.sellingrequest')),
            ],
            options={
                'verbose_name': 'Agent Notification',
                'verbose_name_plural': 'Agent Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
