# Generated by Django 5.2.8 on 2025-12-12 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_agentnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerPrivacySecurity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collect_basic_info', models.BooleanField(default=True, help_text='Collect name, email, phone number, login details')),
                ('collect_property_info', models.BooleanField(default=True, help_text='Collect property information and agreement documents')),
                ('collect_activity_logs', models.BooleanField(default=True, help_text='Collect activity logs related to buying/selling/browsing')),
                ('collect_chat_messages', models.BooleanField(default=True, help_text='Collect chat messages and communications')),
                ('collect_documents', models.BooleanField(default=True, help_text='Collect uploaded documents for compliance')),
                ('collect_optional_info', models.BooleanField(default=False, help_text='Collect optional identity verification files')),
                ('use_for_services', models.BooleanField(default=True, help_text='Use data to provide property search and connection services')),
                ('use_for_cma_reports', models.BooleanField(default=True, help_text='Use data to prepare CMA reports')),
                ('use_for_alerts', models.BooleanField(default=True, help_text='Send alerts about tours, offers, pricing updates')),
                ('use_for_compliance', models.BooleanField(default=True, help_text='Use data for platform security and compliance')),
                ('share_with_partners', models.BooleanField(default=True, help_text='Share with e-signature vendors, payment processors, valuation partners')),
                ('share_with_legal', models.BooleanField(default=True, help_text='Share with legal authorities when required by law')),
                ('allow_multi_factor_auth', models.BooleanField(default=True, help_text='Enable multi-factor authentication')),
                ('encrypted_communication', models.BooleanField(default=True, help_text='Use HTTPS/SSL encryption for sensitive actions')),
                ('data_retention_months', models.IntegerField(default=24, help_text='Keep transaction records and agreement history for X months')),
                ('allow_data_deletion', models.BooleanField(default=True, help_text='Allow user to request data deletion')),
                ('privacy_policy_accepted', models.BooleanField(default=False, help_text='User has accepted privacy policy')),
                ('privacy_policy_version', models.CharField(default='1.0', help_text='Version of accepted privacy policy', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_security', to='seller.seller')),
            ],
            options={
                'verbose_name': 'Seller Privacy & Security',
                'verbose_name_plural': 'Seller Privacy & Security',
            },
        ),
    ]
