# Generated by Django 5.2.8 on 2025-12-13 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_sellerprivacysecurity'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerTermsConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_responsibility', models.BooleanField(default=True, help_text='Accept responsibility for keeping account details accurate and secure')),
                ('service_description_accepted', models.BooleanField(default=False, help_text="Accept the app's service description: browse properties, communicate, request CMA reports, sign agreements")),
                ('accept_digital_agreements', models.BooleanField(default=False, help_text='Accept that app may include legally binding digital agreements (touring, buyer, listing agreements)')),
                ('payment_charges_understood', models.BooleanField(default=False, help_text='Understand all charges will be shown before payment')),
                ('no_fraud', models.BooleanField(default=True, help_text='Agree not to use app for fraud, harassment, unauthorized marketing, data scraping, or illegal activity')),
                ('no_harmful_content', models.BooleanField(default=True, help_text='Agree not to upload harmful, abusive, or copyrighted content without permission')),
                ('terms_version', models.CharField(default='1.0', help_text='Version of accepted terms and conditions', max_length=10)),
                ('terms_accepted_at', models.DateTimeField(blank=True, help_text='When the user accepted the terms', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='terms_conditions', to='seller.seller')),
            ],
            options={
                'verbose_name': 'Seller Terms & Conditions',
                'verbose_name_plural': 'Seller Terms & Conditions',
            },
        ),
    ]
