# Generated by Django 5.2.8 on 2025-12-13 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0007_sellertermsconditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydocument',
            name='cma_document_status',
            field=models.CharField(blank=True, choices=[('accepted', 'Accepted'), ('rejected', 'Rejected')], help_text='Document approval status (accepted or rejected)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='propertydocument',
            name='cma_status',
            field=models.CharField(blank=True, choices=[('accepted', 'Accepted'), ('rejected', 'Rejected')], help_text='Status of the CMA report (accepted or rejected)', max_length=20, null=True),
        ),
    ]
