# Generated by Django 5.2.8 on 2025-12-15 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0008_propertydocument_cma_document_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydocument',
            name='agreement_status',
            field=models.CharField(blank=True, choices=[('accepted', 'Accepted'), ('rejected', 'Rejected')], help_text='Status of the selling agreement (accepted or rejected)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='propertydocument',
            name='selling_agreement_file',
            field=models.FileField(blank=True, help_text='Selling agreement document (PDF, JPG, PNG)', null=True, upload_to='selling_agreements/%Y/%m/%d/'),
        ),
    ]
