# Generated by Django 5.2.5 on 2025-12-20 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0004_showingschedule'),
        ('seller', '0009_propertydocument_agreement_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agentnotification',
            name='agent',
            field=models.ForeignKey(blank=True, help_text='Agent who receives this notification', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agentnotification',
            name='showing_schedule',
            field=models.ForeignKey(blank=True, help_text='Related showing schedule', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_notifications', to='buyer.showingschedule'),
        ),
        migrations.AlterField(
            model_name='agentnotification',
            name='notification_type',
            field=models.CharField(choices=[('document_uploaded', 'Seller Uploaded Document'), ('cma_requested', 'CMA Requested'), ('document_updated', 'Document Updated'), ('new_selling_request', 'New Selling Request'), ('showing_requested', 'Showing Requested')], max_length=50),
        ),
        migrations.AlterField(
            model_name='agentnotification',
            name='selling_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_notifications', to='seller.sellingrequest'),
        ),
    ]
