# Generated by Django 5.2.4 on 2025-12-22 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0010_agentnotification_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
