# Generated by Django 5.2.4 on 2025-12-22 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0011_seller_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Profile image', null=True, upload_to='profile_images/sellers/'),
        ),
    ]
