# Generated by Django 5.2.4 on 2025-12-27 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0013_sellingrequest_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='property_documents/%Y/%m/%d/')),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('original_filename', models.CharField(help_text='Original filename before upload', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='seller.propertydocument')),
            ],
            options={
                'verbose_name': 'Document File',
                'verbose_name_plural': 'Document Files',
                'ordering': ['created_at'],
            },
        ),
    ]
