# Generated by Django 5.2.4 on 2025-12-27 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0014_documentfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertydocument',
            name='file',
        ),
        migrations.RemoveField(
            model_name='propertydocument',
            name='file_size',
        ),
    ]
