# Generated by Django 5.2.4 on 2025-12-27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0015_remove_propertydocument_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellernotification',
            name='cma_document',
            field=models.ForeignKey(blank=True, help_text='Related CMA document for cma_ready notifications', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='seller.propertydocument'),
        ),
    ]
