# Generated by Django 5.2.4 on 2025-12-27

from django.db import migrations

def populate_cma_documents(apps, schema_editor):
    """Populate cma_document field for existing cma_ready notifications"""
    SellerNotification = apps.get_model('seller', 'SellerNotification')
    PropertyDocument = apps.get_model('seller', 'PropertyDocument')
    
    # Get all cma_ready notifications without a cma_document
    notifications = SellerNotification.objects.filter(
        notification_type='cma_ready',
        cma_document__isnull=True
    )
    
    for notification in notifications:
        if notification.selling_request:
            # Find the CMA document for this selling request
            cma_doc = PropertyDocument.objects.filter(
                selling_request=notification.selling_request,
                document_type='cma'
            ).first()
            
            if cma_doc:
                notification.cma_document = cma_doc
                notification.save()

def reverse_populate(apps, schema_editor):
    """Reverse the population"""
    SellerNotification = apps.get_model('seller', 'SellerNotification')
    SellerNotification.objects.filter(
        notification_type='cma_ready'
    ).update(cma_document=None)

class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0016_sellernotification_cma_document'),
    ]

    operations = [
        migrations.RunPython(populate_cma_documents, reverse_populate),
    ]
