# Generated by Django 5.2.4 on 2026-02-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0017_populate_cma_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentnotification',
            name='notification_type',
            field=models.CharField(choices=[('document_uploaded', 'Seller Uploaded Document'), ('cma_requested', 'CMA Requested'), ('document_updated', 'Document Updated'), ('new_selling_request', 'New Selling Request'), ('showing_requested', 'Showing Requested'), ('showing_accepted', 'Showing Accepted'), ('showing_declined', 'Showing Declined')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sellingrequest',
            name='end_date',
            field=models.DateField(blank=True, help_text='When the selling period ends', null=True),
        ),
    ]
