# Generated by Django 5.2.8 on 2025-12-12 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('buyer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='BuyerPrivacySecurity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collect_basic_info', models.BooleanField(default=True, help_text='Collect name, email, phone number, login details')),
                ('collect_property_preferences', models.BooleanField(default=True, help_text='Collect property preferences and search history')),
                ('collect_activity_logs', models.BooleanField(default=True, help_text='Collect activity logs related to property browsing')),
                ('collect_chat_messages', models.BooleanField(default=True, help_text='Collect chat messages with sellers and agents')),
                ('collect_documents', models.BooleanField(default=True, help_text='Collect agreement documents and contracts')),
                ('collect_optional_info', models.BooleanField(default=False, help_text='Collect optional identity verification files')),
                ('use_for_services', models.BooleanField(default=True, help_text='Use data to provide property search services')),
                ('use_for_recommendations', models.BooleanField(default=True, help_text='Use data to recommend properties based on preferences')),
                ('use_for_alerts', models.BooleanField(default=True, help_text='Send alerts about new listings and pricing updates')),
                ('use_for_compliance', models.BooleanField(default=True, help_text='Use data for platform security and compliance')),
                ('share_with_partners', models.BooleanField(default=True, help_text='Share with payment processors and service providers')),
                ('share_with_legal', models.BooleanField(default=True, help_text='Share with legal authorities when required by law')),
                ('allow_multi_factor_auth', models.BooleanField(default=True, help_text='Enable multi-factor authentication')),
                ('encrypted_communication', models.BooleanField(default=True, help_text='Use HTTPS/SSL encryption')),
                ('data_retention_months', models.IntegerField(default=24, help_text='Keep transaction records and agreements for X months')),
                ('allow_data_deletion', models.BooleanField(default=True, help_text='Allow user to request data deletion')),
                ('privacy_policy_accepted', models.BooleanField(default=False, help_text='User has accepted privacy policy')),
                ('privacy_policy_version', models.CharField(default='1.0', help_text='Version of accepted privacy policy', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_security', to='buyer.buyer')),
                ('groups', models.ManyToManyField(blank=True, related_name='buyer_groups', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='buyer_permissions', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Buyer Privacy & Security',
                'verbose_name_plural': 'Buyer Privacy & Security',
            },
        ),
    ]
