# Generated by Django 5.2.5 on 2025-12-20 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0006_propertylisting_propertylistingdocument_and_more'),
        ('buyer', '0003_buyertermsconditions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_date', models.DateField(help_text='Preferred date for showing')),
                ('preferred_time', models.CharField(choices=[('morning', 'Morning (9 AM - 12 PM)'), ('afternoon', 'Afternoon (12 PM - 5 PM)'), ('evening', 'Evening (5 PM - 8 PM)')], default='afternoon', help_text='Preferred time slot', max_length=20)),
                ('additional_notes', models.TextField(blank=True, help_text='Any special requests or questions', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', help_text='Status of the showing request', max_length=20)),
                ('agent_response', models.TextField(blank=True, help_text="Agent's response or notes", null=True)),
                ('responded_at', models.DateTimeField(blank=True, help_text='When the agent responded', null=True)),
                ('confirmed_date', models.DateField(blank=True, help_text='Final confirmed date for showing', null=True)),
                ('confirmed_time', models.TimeField(blank=True, help_text='Final confirmed time for showing', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(help_text='Buyer requesting the showing', on_delete=django.db.models.deletion.CASCADE, related_name='showing_schedules', to='buyer.buyer')),
                ('property_listing', models.ForeignKey(help_text='Property listing to view', on_delete=django.db.models.deletion.CASCADE, related_name='showing_schedules', to='agent.propertylisting')),
            ],
            options={
                'verbose_name': 'Showing Schedule',
                'verbose_name_plural': 'Showing Schedules',
                'ordering': ['-created_at'],
            },
        ),
    ]
