# Generated by Django 5.2.5 on 2025-12-20 23:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0004_showingschedule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('showing_accepted', 'Showing Accepted'), ('showing_declined', 'Showing Declined'), ('showing_reminder', 'Showing Reminder'), ('general', 'General Notification')], default='general', help_text='Type of notification', max_length=50)),
                ('title', models.CharField(help_text='Notification title', max_length=255)),
                ('message', models.TextField(help_text='Notification message')),
                ('is_read', models.BooleanField(default=False, help_text='Whether notification has been read')),
                ('read_at', models.DateTimeField(blank=True, help_text='When notification was read', null=True)),
                ('action_url', models.CharField(blank=True, help_text='URL for action button', max_length=500, null=True)),
                ('action_text', models.CharField(blank=True, help_text='Text for action button', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(help_text='Buyer receiving the notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='buyer.buyer')),
                ('showing_schedule', models.ForeignKey(blank=True, help_text='Related showing schedule', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_notifications', to='buyer.showingschedule')),
            ],
            options={
                'verbose_name': 'Buyer Notification',
                'verbose_name_plural': 'Buyer Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShowingAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_type', models.CharField(choices=[('7_days', '7 Days'), ('one_property', 'One Property Only')], default='one_property', help_text='Duration of the agreement', max_length=50)),
                ('property_address', models.CharField(blank=True, help_text='Property address if applicable', max_length=500, null=True)),
                ('showing_date', models.DateField(help_text='Scheduled showing date')),
                ('signature', models.TextField(help_text='Base64 encoded signature image')),
                ('agreement_accepted', models.BooleanField(default=False, help_text='Whether buyer accepted the terms')),
                ('terms_text', models.TextField(blank=True, help_text='Full text of terms that were accepted', null=True)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(help_text='Agent for the showing', on_delete=django.db.models.deletion.CASCADE, related_name='showing_agreements', to=settings.AUTH_USER_MODEL)),
                ('buyer', models.ForeignKey(help_text='Buyer signing the agreement', on_delete=django.db.models.deletion.CASCADE, related_name='showing_agreements', to='buyer.buyer')),
                ('showing_schedule', models.OneToOneField(help_text='Related showing schedule', on_delete=django.db.models.deletion.CASCADE, related_name='agreement', to='buyer.showingschedule')),
            ],
            options={
                'verbose_name': 'Showing Agreement',
                'verbose_name_plural': 'Showing Agreements',
                'ordering': ['-created_at'],
            },
        ),
    ]
