# Generated by Django 5.2.4 on 2025-12-22 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0005_buyernotification_showingagreement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showingagreement',
            name='signature',
            field=models.TextField(blank=True, help_text="Buyer's digital signature (base64 encoded image or text)", null=True),
        ),
    ]
