# Generated by Django 5.2.4 on 2025-12-22 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0006_alter_showingagreement_signature'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Document title', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Document description', null=True)),
                ('document_file', models.FileField(help_text='Document file (PDF)', upload_to='buyer_documents/%Y/%m/%d/')),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='buyer.buyer')),
            ],
            options={
                'verbose_name': 'Buyer Document',
                'verbose_name_plural': 'Buyer Documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
