# Generated by Django 5.2.4 on 2025-12-22 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0007_buyerdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
