# Generated by Django 5.2.4 on 2025-12-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0009_alter_buyer_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='mortgage_letter',
            field=models.FileField(blank=True, help_text='Mortgage pre-approval letter (PDF, JPG, PNG - max 10MB)', null=True, upload_to='mortgage_letters/buyers/'),
        ),
    ]
