# Generated by Django 5.2.4 on 2025-12-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0010_buyer_mortgage_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerdocument',
            name='document',
            field=models.FileField(blank=True, help_text='Buyer agreement document', null=True, upload_to='buyer_agreements/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='buyerdocument',
            name='document_type',
            field=models.CharField(choices=[('buyer_agreement', 'Buyer Agreement'), ('other', 'Other Document')], default='buyer_agreement', help_text='Type of buyer document', max_length=20),
        ),
    ]
