# Generated by Django 5.2.4 on 2025-12-28 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0011_buyerdocument_document_buyerdocument_document_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyerdocument',
            name='document',
        ),
        migrations.RemoveField(
            model_name='buyerdocument',
            name='document_type',
        ),
    ]
