# Generated by Django 5.2.4 on 2025-12-29 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0012_remove_buyerdocument_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_id', models.IntegerField(help_text='PropertyListing ID that buyer saved')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about why this listing was saved', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_listings', to='buyer.buyer')),
            ],
            options={
                'verbose_name': 'Saved Listing',
                'verbose_name_plural': 'Saved Listings',
                'ordering': ['-created_at'],
                'unique_together': {('buyer', 'listing_id')},
            },
        ),
    ]
